name: CI

on: [push, pull_request]
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cppcheck

    - name: Build
      run: make

    - name: Run tests
      run: make test

    - name: Static analysis
      run: make check
