name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind cppcheck

    - name: Build
      run: make

    - name: Run tests
      run: make test

    - name: Run Valgrind
      run: valgrind --leak-check=full --error-exitcode=1 ./test_runner

    - name: Static analysis
      run: make check

    - name: Check formatting
      run: |
        clang-format --version
        find . -name "*.c" -o -name "*.h" | xargs clang-format --dry-run --Werror